/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	uint32_t *pClkCtrlReg   = (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg  = (uint32_t*)0x40020C14;

	//1. enable the clock for GPIOD peripheral in the AHB1ENR
	*pClkCtrlReg |= (1 << 3);

	//2. configure the mode of the IO pin as output
	//a. clear the 24th and 25th positions
	*pPortDModeReg &= ~(3 << 24);
	//b. make 24 th bit position 1 (SET)
	*pPortDModeReg |= (1 << 24);

	while(1)
	{
	//3. Set 12th bit of the output data register to make IO pin-12 High
	*pPortDOutReg |= (1 << 12);

	for(uint32_t i =0; i < 100000 ; i++);
	*pPortDOutReg &= ~(1 << 12);

	for(uint32_t i =0; i < 100000 ; i++);

	}

}
